"""Generates docs/code-map.md: a Mermaid graph of internal module imports plus orphan modules."""

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUTPUT = ROOT / "docs" / "code-map.md"
ENTRY_POINTS = {"__main__", "main", "app", "server", "cli"}


def module_name(path: Path) -> str:
    parts = path.relative_to(SRC).with_suffix("").parts
    return ".".join(parts[:-1] if parts[-1] == "__init__" else parts)


def resolve(node: ast.ImportFrom, current: str, is_package: bool) -> str:
    if node.level == 0:
        return node.module or ""
    base = current.split(".")
    base = base[: len(base) - node.level + (1 if is_package else 0)]
    return ".".join([*base, node.module] if node.module else base)


def internal_imports(path: Path, modules: set[str]) -> set[str]:
    current = module_name(path)
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            targets = [alias.name for alias in node.names]
        elif isinstance(node, ast.ImportFrom):
            base = resolve(node, current, path.name == "__init__.py")
            targets = [base, *(f"{base}.{alias.name}" for alias in node.names)]
        else:
            continue
        found.update(t for t in targets if t in modules and t != current)
    return found


def main() -> None:
    files = sorted(SRC.rglob("*.py"))
    modules = {module_name(f) for f in files}
    graph = {module_name(f): internal_imports(f, modules) for f in files}
    imported = set().union(*graph.values()) if graph else set()
    orphans = sorted(
        m
        for m in modules
        if m not in imported and "." in m and m.rsplit(".", 1)[-1] not in ENTRY_POINTS
    )

    lines = [
        "# Code map",
        "",
        "Generated by `scripts/code_map.py`. Do not edit by hand.",
        "",
        "```mermaid",
        "graph LR",
    ]
    for source, targets in sorted(graph.items()):
        lines.extend(f"    {source} --> {target}" for target in sorted(targets))
    lines += ["```", "", "## Modules not imported by any other module", ""]
    lines += [f"- `{m}`" for m in orphans] or ["- none"]

    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(modules)} modules, {len(orphans)} orphans)")


if __name__ == "__main__":
    main()
